kind: pipeline
name: default

steps:
  - name: compile
    image: lagmoellertim/google-clojure-compiler
    commands:
      - mkdir dist
      - compile --js hello.js --js_output_file dist/compiled.js
  
  - name: obfuscate
    image: lagmoellertim/js-obfuscator
    commands:
      - obfuscate dist/compiled.js --output dist/compiled-obfuscated.js

  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: dist/compiled-obfuscated.js
    when:
      event: tag
  - name: discord
    image: appleboy/drone-discord
    secrets: [ webhook_id, webhook_token ]
    message: "Compilation nice"