kind: pipeline
name: default

steps:
 - name: compile
   image: lagmoellertim/google-clojure-compiler
   commands:
     - mkdir dist
     - compile --js hello.js --js_output_file dist/compiled.js

 - name: publish
   image: plugins/github-release
   settings:
     api_key: bc526754c66b73d59080118c3b28de1729d75130
     files: dist/compiled.js